services:
  jenkins:
    image: jenkins/jenkins:2.361.2-lts-jdk11
    privileged: true
    ports:
      - 8090:8080
    environment:
      - A=B
    volumes:
      - ./data:/var/jenkins_home
      - ../01-yandex/kubeconfig/config-stage:/root/.kube/config
      - ./jobs:/var/jenkins_home/jobs
      - ./exported-credentials.xml:/var/jenkins_home/exported-credentials.xml
      - /var/run/docker.sock:/var/run/docker.sock
